### ISSUE TITLE
The app is not working under Visual Studio 15.5.4.

### ISSUE THREAD

**Issue by cblf** [GeorgDangl/NetCoreHeroes#1]
The app is not working under Visual Studio 15.5.4.
Despite it compiles well, the component stays in "Loading" state undefinitely.

**Comment by GeorgDangl** [comment]
Hi @cblf, thanks for raising this issue.

Could you tell me which browser you're using? The app was not configured to use polyfills, meaning that it does not work on some browsers that lack certain features.
For example, the app didn't work in Internet Explorer.

Have you tried it with the latest version of Chrome?

Additionally, I've just added polyfills to the app, [see here](https://github.com/GeorgDangl/NetCoreHeroes/blob/master/src/NetCoreHeroes/App/polyfills.ts#L21-L35).
I've enabled all the polyfills required for Internet Explorer.

If it still doesn't work for you, could you try out the online demo: https://netcoreheroes.dangl.me/  (it's running the code that I just commited)
Do you have the same issue there?

**Comment by cblf** [comment]
Hello. Thank you for your answer.
Yes, i am using the latest Chrome. Your online demo does work pretty well, the problem has something to do with Visual Studio itself.
Please notice Visual Studio 2017 now uses Typescript 2.5 by default instead of 2.4 used by your solution.
However, it does compiles right all the way. The problem is all we have on the screen is a "Loading" message.

**Comment by GeorgDangl** [comment]
Can you see what happens when you install TypeScript 2.4 extension for Visual Studio 2017? As far as I remember, the version of Angular in this project (4.1.3) does have issues with TypeScript > 2.4.

Also, could you show me what your browsers console prints? In Chrome, you can open it with `CTRL + SHIFT + J`, it should then look like this:
![unbenannt](https://user-images.githubusercontent.com/10274404/35769468-b61dc130-090b-11e8-80b9-6ce790ce4f45.PNG)

It'll probably show you some error message in red color that should be helpful.
Also, I'll try to find some time to update this project to Angular 5, then it should support TypeScript 2.5.

**Comment by GeorgDangl** [comment]
Oh and additionally, you could try to run the build manually as described in this blog post:
https://blog.dangl.me/archive/netcoreheroes-angular2-with-net-core-in-visual-studio-2015-part-v/

Then it's using TypeScript via npm package. Just to see if the checked out code was correct=)

**Comment by GeorgDangl** [comment]
Soooo, I tinkered with it a bit and now I've upgraded the backend to **netcoreapp2.0** and **Angular 5.2.3.** I've bumped **TypeScript to 2.6.2**, since 2.7 (released just three days ago) didn't work right out of the box for me.

Initially, I just used TypeScript 2.6.2 with the unmodified state of the app, but it was still working for me, both when launched via Visual Studio as well as deployed on IIS. So I'm sorry that I could not reproduce the error, but I'd like to ask you to try it again with the latest changes and see if you've still got trouble running it with Visual Studio 2017.

**Comment by cblf** [comment]
How strange... here is the console output. Apparently the trouble is simply no js files can be found from the startup page. I don't get it because I'm just launching your sample sln and the files are here in the App directory.
![image](https://user-images.githubusercontent.com/11818392/35800925-c1857094-0a6a-11e8-951f-b26eb54e3467.png)

**Comment by GeorgDangl** [comment]
Yeah, this is strange. I guess the resource `vendor.js` is loaded correctly?
Both the missing `polyfills.js` and `main.js` are generated by the Visual Studio binding in `project.json`:

    "-vs-binding": {
      "BeforeBuild": [
        "webpack"
      ]
    }

but.... for this, you need to have the [Task Runner Explorer](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TaskRunnerExplorer) extenstion installed. I didn't include that information in the tutorial when I switched from SystemJS to webpack. A classical "It works on my machine!" bug=)

I've fixed it with db9d391, the webpack build is now controlled directly via the `csproj` project file and should work fine on all machines, as long as the npm modules are installed.

**Comment by cblf** [comment]
Working !
Thank you for the update : as a newbie to angular, it's quite difficult to handle these details.
